### ISSUE TITLE
resnet50 fails on inference /  not detected by unittests

### ISSUE THREAD

**Issue by undertherain** [undertherain/benchmarker#109]
[0]blackbird@sugi:benchmarker$  [master|…2]$ python3 -m benchmarker --framework=pytorch --mode=inference --gpus=0 --problem=resnet50 --problem_size=512,3,224,224 --batch_size=32 --precision=FP32
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/__main__.py", line 14, in <module>
    main()
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/__main__.py", line 10, in main
    run(sys.argv[1:])
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/benchmarker.py", line 89, in run
    benchmark.run()
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/modules/i_neural_net.py", line 88, in run
    results = self.run_internal()
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/modules/do_pytorch.py", line 92, in run_internal
    x_train, y_train = self.load_data()
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/modules/i_neural_net.py", line 71, in load_data
    data = get_data(params)
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/util/data/synthetic/img_224_cls_1000.py", line 13, in get_data
    return gen_classification_data(params, 1000, 224)
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/util/data/synthetic/helpers.py", line 36, in gen_classification_data
    set_image_size(params, height, width)
  File "/home/blackbird/Projects_heavy/performance/benchmarker/benchmarker/util/data/synthetic/helpers.py", line 15, in set_image_size
    params["problem"]["size"] = (params["problem"]["size"],) + shape
UnboundLocalError: local variable 'shape' referenced before assignment

**Comment by undertherain** [comment]
aha, it works if size is not tuple, but one number
just need a normal error message
