### ISSUE TITLE
need to update download paths for travis

### ISSUE THREAD

**Issue by undertherain** [undertherain/benchmarker#130]
https://travis-ci.org/github/undertherain/benchmarker/builds/736254316

```
======================================================================

FAIL: test_res10ssd (test.opencv.test_res10ssd.OpenCvRes10SsdTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/undertherain/benchmarker/test/opencv/test_res10ssd.py", line 20, in test_res10ssd

    run(self.args)

  File "/home/travis/build/undertherain/benchmarker/benchmarker/benchmarker.py", line 85, in run

    benchmark = getattr(mod, "Benchmark")(params, unknown_args)

  File "/home/travis/build/undertherain/benchmarker/benchmarker/modules/do_opencv.py", line 10, in __init__

    super().__init__(params, extra_args)

  File "/home/travis/build/undertherain/benchmarker/benchmarker/modules/i_neural_net.py", line 42, in __init__

    self.get_kernel(params, remaining_args)

  File "/home/travis/build/undertherain/benchmarker/benchmarker/modules/i_neural_net.py", line 62, in get_kernel

    self.net = module_kernel.get_kernel(self.params)

  File "/home/travis/build/undertherain/benchmarker/benchmarker/modules/problems/res10ssd/opencv.py", line 16, in get_kernel

    assert PATH_PROTO.exists(), URL.format(proto, str(BASE))

AssertionError: Download https://github.com/php-opencv/php-opencv-examples/tree/master/models/ssd/res10_300x300_ssd_deploy.prototxt to /home/travis/.cache/benchmarker/models


```
I think Shweta updated somehwere in the code - have to check that it works with wget and update travis script

**Comment by vatai** [comment]
It seems this is the failing download:

```
The command "wget https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp32/versions/1/files/nvidia_ssdpyt_fp32_20190225.pt -O ~/.cache/benchmarker/models/nvidia_ssdpyt_fp32_20190225.pt" failed and exited with 8 during .
```
